### ISSUE TITLE
Discussão - Linguagem PT-BR

### ISSUE THREAD

**Issue by leomaurodesenv** [felipefialho/awesome-made-by-brazilians#105]
Se estamos fazendo uma lista de coisas desenvolvidas por brasileiro, não seria interessante as descrições serem em português?
Nós precisamos auxiliar aqueles que estão começando a programar, e etc.. e ainda temos visto pouca coisa em PT-BR.

**Comment by felipefialho** [comment]
We have already [discussed this here](https://github.com/felipefialho/awesome-made-by-brazilians/issues/33)

The main reason is to give visibility to awesome projects made in Brazil to other parts of the World too 😊
