### ISSUE TITLE
awesome made by brazilians site

### ISSUE THREAD

**Issue by avelino** [felipefialho/awesome-made-by-brazilians#107]
Why? Google Index

What do you think about generating an automated website with the markdown content to go beyond github traffic?

**Comment by felipefialho** [comment]
Can we use some automatic theme about GitHub Pages for now? 🧐

**Comment by avelino** [comment]
Yes, the problem I propose to solve is to use Google to bring traffic. GitHub Pages solves

**Comment by felipefialho** [comment]
Done @avelino 😁

➡️ https://felipefialho.github.io/awesome-made-by-brazilians/

Maybe we need to add a template later hahaha

**Comment by avelino** [comment]
congrats 😄
