### ISSUE TITLE
Create hacktoberfest label

### ISSUE THREAD

**Issue by leogregianin** [felipefialho/awesome-made-by-brazilians#122]
@felipefialho, what do you think about creating a "hacktoberfest" label on issues?

I have a list of really cool projects to include here, but I would like other people to contribute.

https://github.com/haskellcamargo/sclack
The best CLI client for Slack, because everything is terrible!

https://github.com/thumbor/thumbor
thumbor is an open-source photo thumbnail service by globo.com

https://github.com/vsouza/awesome-ios
A curated list of awesome iOS ecosystem, including Objective-C and Swift Projects

https://github.com/doczjs/docz
Has It has never been so easy to document your things!

https://github.com/pedronauck/reworm
Simpl the simplest way to manage state

https://github.com/diegohaz/arc
React starter kit based on Atomic Design

https://github.com/philss/floki
Floki is a simple HTML parser that enables search for nodes using CSS selectors.

**Comment by felipefialho** [comment]
@leogregianin I don't understand, you've suggested of open an issues with some projects to other people contributing?

**Comment by leogregianin** [comment]
Yes @felipefialho, one issue for each project with a tagged hacktoberfest for other peoples contribute.

**Comment by felipefialho** [comment]
For me ok, I'll create a label... 😁

**Comment by leogregianin** [comment]
Create 7 issues: #123 #124 #125 #126 #127 #128 #129
