### ISSUE TITLE
Add philss/floki

### ISSUE THREAD

**Issue by leogregianin** [felipefialho/awesome-made-by-brazilians#129]
Add philss/floki repo:
https://github.com/philss/floki
Floki is a simple HTML parser that enables search for nodes using CSS selectors.

**Comment by ifdiego** [comment]
Hey, I add **floki** some days ago.
At [133](https://github.com/felipefialho/awesome-made-by-brazilians/pull/133)

**Comment by leogregianin** [comment]
Thanks @ifdiego.
