### ISSUE TITLE
Can we add the license badge on the side after the star badge? Would be nice

### ISSUE THREAD

**Issue by terremoth** [felipefialho/awesome-made-by-brazilians#135]
What you guys think?

**Comment by felipefialho** [comment]
Is a good idea.

Can you open a PR with this change? 😁

**Comment by terremoth** [comment]
Of course I can, I'll do it.

**Comment by terremoth** [comment]
Until this weekend I'll do

**Comment by felipefialho** [comment]
It still in progress @terremoth?

**Comment by terremoth** [comment]
Meu deus do céu

**Comment by terremoth** [comment]
Sorry for the fucking big delay: https://github.com/felipefialho/awesome-made-by-brazilians/pull/156
Done.

PS: I created this script to add the license badges: https://gist.github.com/terremoth/423c6a48d0fef89133b3646623d4280d
because I wouldn't do repeated job 😂
