### ISSUE TITLE
Add awesome cypress

### ISSUE THREAD

**Issue by brunopulis** [felipefialho/awesome-made-by-brazilians#151]
Add brunopulis/awesome-cypress repo:

[Awesome Cypress](https://github.com/brunopulis/awesome-cypress)

A curated list of delightful Cypress

**Comment by felipefialho** [comment]
Hey @brunopulis could you open a PR to add it? 😁

**Comment by brunopulis** [comment]
> Hey @brunopulis could you open a PR to add it? 😁

Of course I will open it =)
