### ISSUE TITLE
Translate to portuguese

### ISSUE THREAD

**Issue by danilolmoura** [felipefialho/awesome-made-by-brazilians#33]
I think that to keep an portuguese version too will help those who have some difficulty with English.

I can wait for issue #15 to be finished and send a pull request with a translated document. What do you think?

**Comment by danilolmoura** [comment]
Yeah @felipefialho, on second thought, it really makes sense.

**Comment by felipefialho** [comment]
@danilolmoura I'll close it for now, but we should talk about it again later 😁
