### ISSUE TITLE
Add IntMUD to the list?

### ISSUE THREAD

**Issue by thgcode** [felipefialho/awesome-made-by-brazilians#59]
I was thinking of adding [IntMUD](https://github.com/ed2martin/intmud) to the list. However since it doesn't have many stars for the moment it can't be added but the project is impressive. It is a object-oriented programming language in Portuguese created by [Edward Martin](http://intervox.nce.ufrj.br/~e2mar) for creating server programs. This programming language was created in 2008 and it has features not commonly implemented out-of-the-box on even mainstream programming languages like hot code reloading and the program can easily modify and save its source code while it is running.

**Comment by leogregianin** [comment]
Hi @thgcode, a very interesting project and language but don't have requirements for entry in this list. Can you include in that [list](https://github.com/IonicaBizau/made-in-brazil).
